### ISSUE TITLE
v1.0.0 on npm package

### ISSUE THREAD

**Issue by maruilian11** [appbaseio/appbase-js#16]
hi, we want to host your lib on https://cdnjs.com, I saw v1.0.0 on npm package, it looks strange because the latest version is v0.10.8, and there is no v1.0.0 on github.
I want to confirm do we also need to put v1.0.0 on cdnjs?  
thank you very much!

https://github.com/cdnjs/cdnjs/pull/8914

**Comment by girishramnani** [comment]
the one which connects to this repository is https://www.npmjs.com/package/appbase-js. which is of version v0.10.8 and hence in sync.

**Comment by siddharthlatest** [comment]
@maruilian11 v1.0.0 can be safely ignored. Thanks!

**Comment by PeterDaveHello** [comment]
@siddharthlatest won't there be a new 1.0.0 in the future?

**Comment by siddharthlatest** [comment]
I am working with npmjs support for unpublishing the 1.0.0 version. If that
goes well, we will publish a new 1.0.0 version in the future.

-Siddharth

**Comment by siddharthlatest** [comment]
I am not sure how you include / ignore versions, would a ignored version be
added to a .gitignore file? If we ignore 1.0.0 version now, I am happy to
submit an issue at a later date when we hit the 1.0.0 milestone.

-Siddharth

**Comment by PeterDaveHello** [comment]
@siddharthlatest you are correct, using the `.gitignore` to exlucde the versions been fetched from the auto-updater, thanks for your help, I think we can just add this library with the `.gitignore` mask.

**Comment by siddharthlatest** [comment]
Closing this issue, as we are already past v2.
