### ISSUE TITLE
search() method returns only first 10 results

### ISSUE THREAD

**Issue by girishramnani** [appbaseio/appbase-js#17]
i am trying to do a search query on a type `chats`. I have attached a gist which contains the exported data from dejavu. 
https://gist.github.com/f58c46ee458847358780540093546212

It can be seen that there are more than 28 records but even then when i do a `search` only 10 records are received.

**Comment by yashshah** [comment]
Add size parameter in the query with the number of results you want.  It is
defaulted to 10.

**Comment by girishramnani** [comment]
Is this documented?

**Comment by siddharthlatest** [comment]
It's a FAQ in docs: http://docs.appbase.io/scalr/FAQs/jsapi.html#how-to-change-the-default-results-in-a-search-query.

Closing this issue.
