### ISSUE TITLE
browser lib throws errors and warnings with create-react-app

### ISSUE THREAD

**Issue by corysimmons** [appbaseio/appbase-js#19]
![image](https://cloud.githubusercontent.com/assets/224636/25139101/4bea748c-242a-11e7-9ff7-5432c8e0f985.png)

Propose we break the browser package out, and investigate the constructor thing (since API should match docs [here](http://docs.appbase.io/scalr/javascript/javascript-intro.html#quick-start-to-the-js-api-step-1-lib-setup)).

**Comment by metagrover** [comment]
@divyanshu013 can you test the CRA with `v2.0.0-alpha-03` [UMD build](https://rawgit.com/appbaseio/appbase-js/master/dist/appbase.js)?

**Comment by divyanshu013** [comment]
Verfied with CRA using the UMD build. Works without errors or warnings :clinking_glasses: 
( firefox on linux X64 )

![cra-appbase](https://user-images.githubusercontent.com/6682655/30689902-17411e1c-9ee0-11e7-9ad8-2884191ce94f.png)
