### ISSUE TITLE
WebSocket - Uncaught, unspecified 'error' event

### ISSUE THREAD

**Issue by metagrover** [appbaseio/appbase-js#28]
Platform: IOS - React Native

![screen shot 2017-11-09 at 3 20 02 pm](https://user-images.githubusercontent.com/9116042/32599144-a1248054-c561-11e7-88eb-b90bfb659b61.png)

**Comment by metagrover** [comment]
The issue was at the server-end. Not related to appbase-js

**Comment by generalomosco** [comment]
I went into `nodes-modules/appbase-js/lib/better_websocket.js`  and add `try` to the error event

From
```

conn.onerror = function (err) {
          ee.emit("error", err);
	};
```

To
```
conn.onerror = function (err) {
    try {
      ee.emit("error", err);
    } catch(e) {

    }
	};
```
