### ISSUE TITLE
Vue plug-in available? 

### ISSUE THREAD

**Issue by farmanp** [appbaseio/appbase-js#40]
Is there a Vue plug-in available for this library? I’m current using Vue for my application and think this search capability would be great but I noticed this is mainly for React. What alternatives or workarounds might you recommend?

**Comment by divyanshu013** [comment]
Hi, if you're only using `appbase-js` it should work anywhere be it react, vue or node since this is independent of react. ReactiveSearch, on the other hand, is dependent on react.

**Comment by siddharthlatest** [comment]
I want to add here that we are considering ReactiveSearch for `Vue`, although we don't have a concrete roadmap for it. Initial support for it would have limited components.
