### ISSUE TITLE
Add include: credentials support

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/appbase-js#42]
Since the underlying request is a `fetch` we could support this in the coming version

**Comment by Timothylawler** [comment]
To add to this suggestion:

This is for authenticating requests with cookie.

This is currently possible by patching it in the request before firing:

```javascript
const Base = ({ children }) => {
  const onBeforeSend = props => {
    return {
      ...props,
      credentials: 'include',
    }
  }

  return (
    <ReactiveBase
      app="app-name"
      url="url"
      beforeSend={onBeforeSend}
    >
      {children}
    </ReactiveBase>
  )
}
```

**Comment by stirlingalgermissen** [comment]
Is it possible to prioritize this request?
