### ISSUE TITLE
Publish the package pre-compiled

### ISSUE THREAD

**Issue by tureba** [appbaseio/appbase-js#45]
Hi,

I've been trying to build a project that consumes reactivesearch+appbase-js but I get this output:

```
> node scripts/build.js

Creating an optimized production build...
0% compiling
10% building modules
18.04% building modules
26.08% building modules
34.12% building modules
42.16% building modules
50.2% building modules
58.24% building modules
66.28% building modules
71% sealing
72% optimizing
73% basic module optimization
74% module optimization
75% advanced module optimization
76% basic chunk optimization
77% chunk optimization
78% advanced chunk optimization
79% module and chunk tree optimization
80% chunk modules optimization
81% advanced chunk modules optimization
82% module reviving
83% module order optimization
84% module id optimization
85% chunk reviving
86% chunk order optimization
87% chunk id optimization
88% hashing
89% module assets processing
90% chunk assets processing
91% additional chunk assets processing
92% recording
91% additional asset processing
92% chunk asset optimization
94% asset optimization
95% emitting
100%
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/appbase-js/dist/appbase-js.es.js:12

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superplano@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superplano@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
[...]
```

Following the reference link brings me to this description:

## npm run build fails to minify
Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

To resolve this:
- Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.
Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.
- Fork the package and publish a corrected version yourself.

- If the dependency is small enough, copy it to your src/ folder and treat it as application code.

In the future, we might start automatically compiling incompatible third-party modules, but it is not currently supported. This approach would also slow down the production builds.

## Conclusion

That's why I'm asking here for this package to be published pre-compiled as facebook's create-react-app instructs us.

Thanks

**Comment by bietkul** [comment]
Please try to update your `appbase-js` version, it has been fixed in the latest.

**Comment by tureba** [comment]
Ah, I see that now. It seems that the combo reactivesearch@2.9.1 plus appbase-js@4.0.2-beta.02 fixes it for me.
Thanks!

**Comment by siddharthlatest** [comment]
Hi Arthur,

This has been fixed in the latest release. You can upgrade reactivesearch
to 2.9.1, and you won't see this issue.

Thanks,
-Siddharth
