### ISSUE TITLE
getStream() throws an error "method does not support streaming." when a document does not exist

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/appbase-js#7]
A document with a non-existent id throws the following error:
![](https://i.imgur.com/lZxcd0K.png)

Since `get()` on a non-existent document returns a JSON object with a field "found" set to `false`, `getStream()` should a response message to the effect:

"document with type `:type` and id `:id` cannot be found."

**Comment by siddharthlatest** [comment]
This is interesting as ``searchStream()`` does not return an error when the ``:type`` does not exist.

**Comment by sacheendra** [comment]
This is because, when there is no document the GET returns a 404. Therefore, it is saying that GET /doc_that_does_not_exist is a method that does not support streaming.

**Comment by siddharthlatest** [comment]
It should return an error, that's correct. But an appropriate message would be "document with type :type and id :id cannot be found." over "This method does not support streaming".
